/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvatarUpload: typeof import('./src/components/avatar-upload/index.vue')['default']
    CropperCanvas: typeof import('./src/components/avatar-upload/cropper-canvas.vue')['default']
    ImageCropper: typeof import('./src/components/ImageCropper/ImageCropper.vue')['default']
    LanguageSelector: typeof import('./src/components/language-selector.vue')['default']
    NavBar: typeof import('./src/components/nav-bar.vue')['default']
    UvAvatar: typeof import('./src/components/uv-avatar/uv-avatar.vue')['default']
    WdConfigProvider: typeof import('wot-design-uni/components/wd-config-provider/wd-config-provider.vue')['default']
  }
}
